services:
  postgres:
    image: postgres:16-alpine
    container_name: evolution_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: evolution_db
      POSTGRES_USER: evolution
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - evolution_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U evolution -d evolution_db"]
      interval: 5s
      timeout: 5s
      retries: 20

    networks:
      - evolution_network


  redis:
    image: redis:7-alpine
    container_name: evolution_redis
    restart: unless-stopped

    command:
      - redis-server
      - --appendonly
      - "yes"
      - --requirepass
      - "${REDIS_PASSWORD}"

    volumes:
      - evolution_redis_data:/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "redis-cli -a \"$${REDIS_PASSWORD}\" ping | grep PONG"
        ]
      interval: 5s
      timeout: 5s
      retries: 20

    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

    networks:
      - evolution_network


  evolution-api:
    build:
      context: .
      dockerfile: Dockerfile

    image: evolution-api-local:2.3.7
    container_name: evolution_api
    restart: unless-stopped

    env_file:
      - .env

    environment:
      DATABASE_PROVIDER: postgresql
      DATABASE_CONNECTION_URI: postgresql://evolution:${POSTGRES_PASSWORD}@postgres:5432/evolution_db?schema=evolution_api

      CACHE_REDIS_ENABLED: "true"
      CACHE_REDIS_URI: redis://:${REDIS_PASSWORD}@redis:6379/6
      CACHE_REDIS_PREFIX_KEY: evolution
      CACHE_REDIS_SAVE_INSTANCES: "true"
      CACHE_LOCAL_ENABLED: "false"

      SERVER_PORT: "8080"
      TZ: Asia/Almaty

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    ports:
      - "8080:8080"

    volumes:
      - evolution_instances:/evolution/instances

    networks:
      - evolution_network


  evolution-manager:
    image: evoapicloud/evolution-manager:latest
    container_name: evolution_frontend
    restart: unless-stopped

    depends_on:
      evolution-api:
        condition: service_started

    ports:
      - "8081:80"

    volumes:
      - ./Docker/evolution-manager/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro

    networks:
      - evolution_network


volumes:
  evolution_postgres_data:
  evolution_redis_data:
  evolution_instances:


networks:
  evolution_network:
    name: evolution_network
    driver: bridge